### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [turnage/turnage.github.io#2]
Hi! I am the editor of [Haskell Weekly](https://haskellweekly.news). I would like to be notified when you write a new post, but as far as I can tell your blog does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by turnage** [comment]
Hi this is an exciting issue to see! I added a [feed](https://paytonturnage.com/feed.xml).

**Comment by tfausak** [comment]
:tada: Thank you!
